// src/utils/avatars.js

export const AVATARS = [
  { id: 0, avatar: "🐶" },
  { id: 1, avatar: "🐱" },
  { id: 2, avatar: "🐰" },
  { id: 3, avatar: "🦊" },
  { id: 4, avatar: "🐼" },
  { id: 5, avatar: "🐨" },
  { id: 6, avatar: "🦁" },
  { id: 7, avatar: "🐸" },
  { id: 8, avatar: "🐵" },
  { id: 9, avatar: "🐧" },
  { id: 10, avatar: "🦄" },
  { id: 11, avatar: "🐹" },
  { id: 12, avatar: "🐺" },
  { id: 13, avatar: "🤖" },
  { id: 14, avatar: "👻" },
  { id: 15, avatar: "👽" },
  { id: 16, avatar: "🎃" },
  { id: 17, avatar: "🧙" },
  { id: 18, avatar: "🌸" },
  { id: 19, avatar: "🪐" },
  { id: 20, avatar: "💎" },
  { id: 21, avatar: "⭐" },
];
